### ISSUE TITLE
Print label no longer displayed on re-designed lichess page

### ISSUE THREAD

**Issue by PhilW32** [ZeroSharp/lichess.org_pdf_Chrome_extension#1]
Hi Robert, thanks for a great chrome extension, I use it to pretty print my lichess chess games. Since the 9th June 2022 or thereabouts however, the lichess web pages have been re-designed and re-named and the print label that triggers the extension no longer appears.

Within the "Analysis Board" section of the webpages, the old "FEN & PGN" page has been renamed to ""Share & Export", and has been re-designed.

I have my fingers crossed that the fix is straight-forward and that you have a moment or two to implement it.  Thanks again for a great piece of software.

**Comment by shamp00** [comment]
Great to hear you enjoy the extension. I had no idea it had stopped working - I'm not playing much chess these days, so thanks for letting me know. I'll take a look.

**Comment by shamp00** [comment]
@PhilW32 the fix has just gone live (version 3.0.0). It took a few days for the Chrome extension team to approve it, but it should be working again now. Let me know if you have any trouble.

**Comment by PhilW32** [comment]
Hi Robert, that's great, thank you.  I attach a new screenshot for your use whenever you need one;  also I offer to submit a note to the Lichess Forums to let other users know of your fantastic extension if you think that's a good idea.

Thanks again, kind regards
Phil
![Lichess print friendly screenshot for v3 0](https://user-images.githubusercontent.com/107305047/175063627-93ce9914-70ba-4358-883b-dfb9fadb6922.png)
.

**Comment by shamp00** [comment]
Sure that would be great!
